# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := core network protocol UnitTest SoakProtocol SoakClientServer ProfileProtocol ProfileClientServer FontBuilder Client Server

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

core: 
	@echo "==== Building core ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f core.make

network: core
	@echo "==== Building network ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f network.make

protocol: core network
	@echo "==== Building protocol ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f protocol.make

UnitTest: core network protocol
	@echo "==== Building UnitTest ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f UnitTest.make

SoakProtocol: core network protocol
	@echo "==== Building SoakProtocol ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f SoakProtocol.make

SoakClientServer: core network protocol
	@echo "==== Building SoakClientServer ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f SoakClientServer.make

ProfileProtocol: core network protocol
	@echo "==== Building ProfileProtocol ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f ProfileProtocol.make

ProfileClientServer: core network protocol
	@echo "==== Building ProfileClientServer ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f ProfileClientServer.make

FontBuilder: core
	@echo "==== Building FontBuilder ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f FontBuilder.make

Client: core network protocol
	@echo "==== Building Client ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Client.make

Server: core network protocol
	@echo "==== Building Server ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Server.make

clean:
	@${MAKE} --no-print-directory -C . -f core.make clean
	@${MAKE} --no-print-directory -C . -f network.make clean
	@${MAKE} --no-print-directory -C . -f protocol.make clean
	@${MAKE} --no-print-directory -C build -f UnitTest.make clean
	@${MAKE} --no-print-directory -C build -f SoakProtocol.make clean
	@${MAKE} --no-print-directory -C build -f SoakClientServer.make clean
	@${MAKE} --no-print-directory -C build -f ProfileProtocol.make clean
	@${MAKE} --no-print-directory -C build -f ProfileClientServer.make clean
	@${MAKE} --no-print-directory -C build -f FontBuilder.make clean
	@${MAKE} --no-print-directory -C build -f Client.make clean
	@${MAKE} --no-print-directory -C build -f Server.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   core"
	@echo "   network"
	@echo "   protocol"
	@echo "   UnitTest"
	@echo "   SoakProtocol"
	@echo "   SoakClientServer"
	@echo "   ProfileProtocol"
	@echo "   ProfileClientServer"
	@echo "   FontBuilder"
	@echo "   Client"
	@echo "   Server"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
