# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := protocol UnitTest SoakTest Profile

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

protocol: 
	@echo "==== Building protocol ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f protocol.make

UnitTest: protocol
	@echo "==== Building UnitTest ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f UnitTest.make

SoakTest: protocol
	@echo "==== Building SoakTest ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f SoakTest.make

Profile: protocol
	@echo "==== Building Profile ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Profile.make

clean:
	@${MAKE} --no-print-directory -C . -f protocol.make clean
	@${MAKE} --no-print-directory -C build -f UnitTest.make clean
	@${MAKE} --no-print-directory -C build -f SoakTest.make clean
	@${MAKE} --no-print-directory -C build -f Profile.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   protocol"
	@echo "   UnitTest"
	@echo "   SoakTest"
	@echo "   Profile"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
